/* ==========================================================================
   RestaurantOS Primary State Store & Master Initial Data
   ========================================================================== */

const STORAGE_KEY = 'restaurantos_store_v3';

const initialStore = {
  restaurant: {
    name: "RestaurantOS Andhra Kitchen",
    tagline: "The Complete AI-Powered Restaurant Management Platform for Modern Restaurants",
    phone: "+91 98765 43210",
    address: "Indiranagar 100ft Road, Bengaluru, Karnataka 560038",
    taxRate: 5,
    deliveryFee: 50
  },

  stats: {
    todayRevenue: 54950,
    todayOrders: 72,
    pendingOrders: 6,
    aov: 763
  },

  categories: [
    { id: "all", name: "All Dishes", icon: "fa-border-all", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=200&q=80" },
    { id: "biryani", name: "Andhra Biryanis", icon: "fa-bowl-rice", image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=200&q=80" },
    { id: "meals", name: "Traditional Meals", icon: "fa-plate-wheat", image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=200&q=80" },
    { id: "curries", name: "Curries & Gravies", icon: "fa-pepper-hot", image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=200&q=80" },
    { id: "starters", name: "Crispy Starters", icon: "fa-drumstick-bite", image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=200&q=80" },
    { id: "beverages", name: "Popular Beverages", icon: "fa-glass-water", image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=200&q=80" },
    { id: "pickles", name: "Andhra Pickles", icon: "fa-jar", image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=300&q=80" },
    { id: "extras", name: "Extras & Sides", icon: "fa-utensils", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=200&q=80" }
  ],

  menuItems: [
    // 1. BIRYANIS
    {
      id: "item-biryani-1",
      name: "Andhra Chicken Biryani",
      category: "biryani",
      price: 349,
      originalPrice: 399,
      discount: 12,
      description: "Spicy aromatic basmati rice dum-cooked with tender succulent chicken pieces and traditional Andhra spices.",
      isVeg: false,
      badge: "BESTSELLER",
      prepTime: "15 mins",
      rating: 4.9,
      reviewsCount: 420,
      ingredients: ["Basmati Rice", "Chicken", "Ghee", "Andhra Spices"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 50
    },
    {
      id: "item-biryani-2",
      name: "Mutton Dum Biryani",
      category: "biryani",
      price: 449,
      originalPrice: 499,
      discount: 10,
      description: "Slow-cooked tender bone-in mutton marinated in yogurt & spices layered with fragrant saffron basmati rice.",
      isVeg: false,
      badge: "MUST TRY",
      prepTime: "18 mins",
      rating: 4.95,
      reviewsCount: 310,
      ingredients: ["Mutton", "Basmati Rice", "Saffron", "Fried Onions"],
      image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 35
    },
    {
      id: "item-biryani-3",
      name: "Prawn Biryani",
      category: "biryani",
      price: 429,
      originalPrice: 479,
      discount: 10,
      description: "Fresh juicy tiger prawns marinated in coastal Andhra spices, cooked with long-grain basmati rice.",
      isVeg: false,
      badge: "CHEF SPECIAL",
      prepTime: "15 mins",
      rating: 4.85,
      reviewsCount: 190,
      ingredients: ["Tiger Prawns", "Basmati Rice", "Curry Leaves", "Ghee"],
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 30
    },
    {
      id: "item-biryani-4",
      name: "Ulavacharu Biryani",
      category: "biryani",
      price: 379,
      originalPrice: 429,
      discount: 11,
      description: "Unique Andhra delicacy biryani infused with rich horsegram soup broth (Ulavacharu) & tender chicken.",
      isVeg: false,
      badge: "SPECIAL",
      prepTime: "15 mins",
      rating: 4.8,
      reviewsCount: 245,
      ingredients: ["Horsegram Broth", "Chicken", "Basmati Rice", "Desi Ghee"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 25
    },
    {
      id: "item-biryani-5",
      name: "Chicken Fry Piece Biryani",
      category: "biryani",
      price: 369,
      originalPrice: 419,
      discount: 12,
      description: "Fragrant biryani rice served with crispy spicy Andhra style fried chicken pieces on top.",
      isVeg: false,
      badge: "POPULAR",
      prepTime: "15 mins",
      rating: 4.88,
      reviewsCount: 380,
      ingredients: ["Fried Chicken", "Biryani Rice", "Green Chillies", "Ghee"],
      image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 40
    },

    // 2. MEALS & RICE
    {
      id: "item-meals-1",
      name: "Andhra Meals",
      category: "meals",
      price: 299,
      originalPrice: 349,
      discount: 14,
      description: "Full thali meal served with Sona Masoori rice, Pappu, Sambar, Rasam, Majjiga, Avakaya pickle, Papad & Ghee.",
      isVeg: true,
      badge: "AUTHENTIC",
      prepTime: "10 mins",
      rating: 4.9,
      reviewsCount: 510,
      ingredients: ["Steamed Rice", "Dal", "Sambar", "Rasam", "Pickle", "Ghee"],
      image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 60
    },
    {
      id: "item-meals-2",
      name: "Veg Meals",
      category: "meals",
      price: 249,
      originalPrice: 289,
      discount: 13,
      description: "Traditional pure veg meal thali with seasonal vegetable fry, Pappu, Sambar, Rasam, Curd & Papad.",
      isVeg: true,
      badge: "PURE VEG",
      prepTime: "10 mins",
      rating: 4.75,
      reviewsCount: 320,
      ingredients: ["Veg Fry", "Rice", "Pappu", "Curd", "Papad"],
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 60
    },
    {
      id: "item-meals-3",
      name: "Curd Rice",
      category: "meals",
      price: 149,
      originalPrice: 179,
      discount: 16,
      description: "Soothing fresh curd rice tempered with mustard seeds, curry leaves, ginger & green chillies.",
      isVeg: true,
      badge: "SOOTHING",
      prepTime: "5 mins",
      rating: 4.85,
      reviewsCount: 290,
      ingredients: ["Fresh Curd", "Rice", "Mustard", "Curry Leaves"],
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 50
    },
    {
      id: "item-meals-4",
      name: "Ghee Rice",
      category: "meals",
      price: 189,
      originalPrice: 219,
      discount: 13,
      description: "Aromatic basmati rice cooked in pure desi ghee with whole spices, cashews & fried onions.",
      isVeg: true,
      badge: "AROMATIC",
      prepTime: "10 mins",
      rating: 4.7,
      reviewsCount: 210,
      ingredients: ["Desi Ghee", "Basmati Rice", "Cashews", "Spices"],
      image: "https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 45
    },

    // 3. CURRIES & GRAVIES
    {
      id: "item-curry-1",
      name: "Gongura Chicken",
      category: "curries",
      price: 329,
      originalPrice: 379,
      discount: 13,
      description: "Iconic Andhra curry with tender chicken cooked in tangy, spicy sorrel leaves (Gongura) masala gravy.",
      isVeg: false,
      badge: "SIGNATURE",
      prepTime: "15 mins",
      rating: 4.9,
      reviewsCount: 360,
      ingredients: ["Gongura Leaves", "Chicken", "Red Chillies", "Spices"],
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 35
    },
    {
      id: "item-curry-2",
      name: "Gongura Mutton",
      category: "curries",
      price: 419,
      originalPrice: 469,
      discount: 10,
      description: "Rich mutton curry infused with authentic sour Gongura sorrel paste & roasted red chilli spices.",
      isVeg: false,
      badge: "CHEF RECOMMEND",
      prepTime: "18 mins",
      rating: 4.92,
      reviewsCount: 280,
      ingredients: ["Mutton", "Gongura Leaves", "Garlic", "Spices"],
      image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 25
    },
    {
      id: "item-curry-3",
      name: "Natukodi Pulusu",
      category: "curries",
      price: 389,
      originalPrice: 439,
      discount: 11,
      description: "Traditional rustic country chicken (Natukodi) cooked in a fiery tangy tamarind gravy.",
      isVeg: false,
      badge: "COUNTRY SPECIAL",
      prepTime: "20 mins",
      rating: 4.88,
      reviewsCount: 230,
      ingredients: ["Country Chicken", "Tamarind", "Chilli Powder", "Onions"],
      image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 30
    },
    {
      id: "item-curry-4",
      name: "Royyala Iguru (Prawn Curry)",
      category: "curries",
      price: 429,
      originalPrice: 479,
      discount: 10,
      description: "Thick semi-dry coastal prawn curry cooked with caramelised onions, green chillies & spices.",
      isVeg: false,
      badge: "SPICY",
      prepTime: "15 mins",
      rating: 4.82,
      reviewsCount: 195,
      ingredients: ["Fresh Prawns", "Onions", "Curry Leaves", "Garam Masala"],
      image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 25
    },
    {
      id: "item-curry-5",
      name: "Chepala Pulusu",
      category: "curries",
      price: 369,
      originalPrice: 409,
      discount: 10,
      description: "Tangy Andhra fish curry stewed in tamarind sauce with fenugreek seeds & fresh green chillies.",
      isVeg: false,
      badge: "FISH SPECIAL",
      prepTime: "15 mins",
      rating: 4.8,
      reviewsCount: 175,
      ingredients: ["Fresh Fish", "Tamarind", "Fenugreek", "Chillies"],
      image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 25
    },
    {
      id: "item-curry-6",
      name: "Paneer Butter Masala",
      category: "curries",
      price: 299,
      originalPrice: 339,
      discount: 11,
      description: "Soft cottage cheese cubes simmered in a rich, buttery tomato & cashew nut gravy.",
      isVeg: true,
      badge: "CLASSIC",
      prepTime: "12 mins",
      rating: 4.75,
      reviewsCount: 310,
      ingredients: ["Paneer", "Butter", "Cashew Gravy", "Kasuri Methi"],
      image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 40
    },
    {
      id: "item-curry-7",
      name: "Mushroom Curry",
      category: "curries",
      price: 289,
      originalPrice: 329,
      discount: 12,
      description: "Fresh button mushrooms tossed in a flavorful onion, tomato & coconut masala gravy.",
      isVeg: true,
      badge: "POPULAR",
      prepTime: "12 mins",
      rating: 4.65,
      reviewsCount: 180,
      ingredients: ["Mushrooms", "Tomato", "Coconut", "Spices"],
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 35
    },
    {
      id: "item-curry-8",
      name: "Gutti Vankaya Curry",
      category: "curries",
      price: 269,
      originalPrice: 299,
      discount: 10,
      description: "Stuffed small brinjals (eggplant) cooked in roasted peanut, sesame & tamarind gravy.",
      isVeg: true,
      badge: "ANDHRA SPECIAL",
      prepTime: "12 mins",
      rating: 4.85,
      reviewsCount: 260,
      ingredients: ["Small Brinjal", "Peanut Paste", "Sesame", "Tamarind"],
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 30
    },
    {
      id: "item-curry-9",
      name: "Pappu Charu",
      category: "curries",
      price: 179,
      originalPrice: 199,
      discount: 10,
      description: "Homestyle Andhra lentil stew seasoned with mustard seeds, curry leaves & asafoetida.",
      isVeg: true,
      badge: "TRADITIONAL",
      prepTime: "10 mins",
      rating: 4.8,
      reviewsCount: 340,
      ingredients: ["Toor Dal", "Tamarind", "Mustard", "Ghee"],
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 45
    },
    {
      id: "item-curry-10",
      name: "Sambar",
      category: "curries",
      price: 149,
      originalPrice: 169,
      discount: 11,
      description: "Aromatic lentil stew cooked with drumsticks, pumpkin, tomatoes & homemade sambar masala.",
      isVeg: true,
      badge: "HOMESTYLE",
      prepTime: "10 mins",
      rating: 4.7,
      reviewsCount: 280,
      ingredients: ["Lentils", "Drumstick", "Tomato", "Sambar Powder"],
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 50
    },
    {
      id: "item-curry-11",
      name: "Rasam",
      category: "curries",
      price: 129,
      originalPrice: 149,
      discount: 13,
      description: "Fiery pepper & tomato soup broth infused with garlic, cumin, coriander & tamarind.",
      isVeg: true,
      badge: "SPICED SOUP",
      prepTime: "5 mins",
      rating: 4.9,
      reviewsCount: 410,
      ingredients: ["Black Pepper", "Tamarind", "Garlic", "Cumin"],
      image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 50
    },

    // 4. STARTERS
    {
      id: "item-starter-1",
      name: "Apollo Fish",
      category: "starters",
      price: 359,
      originalPrice: 399,
      discount: 10,
      description: "Boneless fish fillets marinated in spicy red chilli batter, fried crispy and tossed in yogurt garlic sauce.",
      isVeg: false,
      badge: "SEAFOOD STARTER",
      prepTime: "12 mins",
      rating: 4.88,
      reviewsCount: 290,
      ingredients: ["Fish Fillet", "Yogurt Sauce", "Chillies", "Garlic"],
      image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 35
    },
    {
      id: "item-starter-2",
      name: "Chicken 65",
      category: "starters",
      price: 299,
      originalPrice: 339,
      discount: 11,
      description: "Classic deep-fried chicken cubes coated in spicy ginger, garlic, red chilli & curry leaf masala.",
      isVeg: false,
      badge: "CRISPY",
      prepTime: "12 mins",
      rating: 4.85,
      reviewsCount: 450,
      ingredients: ["Chicken", "Curry Leaves", "Garlic", "Red Chilli"],
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 45
    },
    {
      id: "item-starter-3",
      name: "Chilli Chicken",
      category: "starters",
      price: 299,
      originalPrice: 339,
      discount: 11,
      description: "Crispy chicken morsels wok-tossed with fresh green chillies, capsicum, garlic & soy glaze.",
      isVeg: false,
      badge: "HOT & SPICY",
      prepTime: "12 mins",
      rating: 4.8,
      reviewsCount: 380,
      ingredients: ["Chicken", "Green Chillies", "Capsicum", "Soy Sauce"],
      image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 40
    },
    {
      id: "item-starter-4",
      name: "Pepper Chicken",
      category: "starters",
      price: 309,
      originalPrice: 349,
      discount: 11,
      description: "Pan-fried chicken pieces tossed in freshly crushed black pepper corns, curry leaves & shallots.",
      isVeg: false,
      badge: "PEPPER SPECIAL",
      prepTime: "12 mins",
      rating: 4.82,
      reviewsCount: 270,
      ingredients: ["Chicken", "Crushed Black Pepper", "Curry Leaves", "Ghee"],
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 40
    },

    // 5. DESSERTS
    {
      id: "item-dessert-1",
      name: "Double Ka Meetha",
      category: "desserts",
      price: 169,
      originalPrice: 199,
      discount: 15,
      description: "Hyderabadi bread pudding fried in pure ghee, soaked in saffron cardamon rabri milk & topped with nuts.",
      isVeg: true,
      badge: "ROYAL DESSERT",
      prepTime: "5 mins",
      rating: 4.9,
      reviewsCount: 310,
      ingredients: ["Bread", "Desi Ghee", "Saffron Rabri", "Almonds"],
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 30
    },

    // 6. POPULAR BEVERAGES
    {
      id: "item-bev-1",
      name: "Buttermilk (Majjiga)",
      category: "beverages",
      price: 59,
      originalPrice: 69,
      discount: 14,
      description: "Chilled spiced buttermilk blended with crushed ginger, green chillies, coriander & curry leaves.",
      isVeg: true,
      badge: "COOLING",
      prepTime: "2 mins",
      rating: 4.95,
      reviewsCount: 520,
      ingredients: ["Curd", "Ginger", "Curry Leaves", "Salt"],
      image: "https://images.unsplash.com/photo-1626078436896-e2a225492d52?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 80
    },
    {
      id: "item-bev-2",
      name: "Fresh Lime Soda",
      category: "beverages",
      price: 69,
      originalPrice: 79,
      discount: 12,
      description: "Freshly squeezed lime juice served over sparkling soda (Sweet / Salted / Mixed).",
      isVeg: true,
      badge: "REFRESHING",
      prepTime: "2 mins",
      rating: 4.8,
      reviewsCount: 290,
      ingredients: ["Fresh Lime", "Sparkling Soda", "Mint", "Ice"],
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 80
    },
    {
      id: "item-bev-3",
      name: "Sweet Lassi",
      category: "beverages",
      price: 89,
      originalPrice: 99,
      discount: 10,
      description: "Thick creamy churned sweet yogurt drink garnished with cardamom powder and saffron.",
      isVeg: true,
      badge: "CREAMY",
      prepTime: "3 mins",
      rating: 4.85,
      reviewsCount: 240,
      ingredients: ["Yogurt", "Sugar", "Cardamom", "Nuts"],
      image: "https://images.unsplash.com/photo-1571006682878-360e5fa33e8b?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 60
    },
    {
      id: "item-bev-4",
      name: "Badam Milk",
      category: "beverages",
      price: 99,
      originalPrice: 119,
      discount: 16,
      description: "Rich chilled almond milk flavored with saffron strand, cardamom and crushed almonds.",
      isVeg: true,
      badge: "RICH",
      prepTime: "3 mins",
      rating: 4.9,
      reviewsCount: 180,
      ingredients: ["Almonds", "Milk", "Saffron", "Cardamom"],
      image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 50
    },
    {
      id: "item-bev-5",
      name: "Mango Juice",
      category: "beverages",
      price: 79,
      originalPrice: 89,
      discount: 11,
      description: "Fresh pulp juice made from ripe Alphonso mangoes, served ice-chilled.",
      isVeg: true,
      badge: "SEASONAL",
      prepTime: "2 mins",
      rating: 4.8,
      reviewsCount: 220,
      ingredients: ["Mango Pulp", "Ice", "Sugar"],
      image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 60
    },
    {
      id: "item-bev-6",
      name: "Soft Drinks",
      category: "beverages",
      price: 49,
      originalPrice: 59,
      discount: 16,
      description: "Chilled 330ml aerated soft drink bottle (Thums Up / Coke / Sprite).",
      isVeg: true,
      badge: "CHILLED",
      prepTime: "1 min",
      rating: 4.6,
      reviewsCount: 350,
      ingredients: ["Aerated Water", "Flavor"],
      image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-bev-7",
      name: "Mineral Water",
      category: "beverages",
      price: 25,
      originalPrice: 30,
      discount: 16,
      description: "1 Liter packaged purified drinking mineral water bottle.",
      isVeg: true,
      badge: "PACKAGED",
      prepTime: "1 min",
      rating: 4.9,
      reviewsCount: 600,
      ingredients: ["Purified Water"],
      image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 150
    },

    // 7. ANDHRA PICKLES
    {
      id: "item-pickle-1",
      name: "Avakaya Pickle",
      category: "pickles",
      price: 49,
      originalPrice: 59,
      discount: 16,
      description: "Authentic spicy raw mango pickle seasoned with mustard powder, red chilli & sesame oil.",
      isVeg: true,
      badge: "MANGO SPICE",
      prepTime: "1 min",
      rating: 4.95,
      reviewsCount: 480,
      ingredients: ["Raw Mango", "Mustard Powder", "Sesame Oil", "Chillies"],
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-pickle-2",
      name: "Gongura Pickle",
      category: "pickles",
      price: 49,
      originalPrice: 59,
      discount: 16,
      description: "Traditional tangy sorrel leaf pickle ground with garlic cloves & dried red chillies.",
      isVeg: true,
      badge: "SORREL LEAF",
      prepTime: "1 min",
      rating: 4.9,
      reviewsCount: 390,
      ingredients: ["Gongura Leaves", "Garlic", "Red Chilli", "Oil"],
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-pickle-3",
      name: "Tomato Pickle",
      category: "pickles",
      price: 49,
      originalPrice: 59,
      discount: 16,
      description: "Spicy sun-dried tomato chutney pickle tempered with mustard, cumin & garlic.",
      isVeg: true,
      badge: "SPICY TOMATO",
      prepTime: "1 min",
      rating: 4.8,
      reviewsCount: 230,
      ingredients: ["Ripe Tomatoes", "Garlic", "Mustard", "Oil"],
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-pickle-4",
      name: "Lemon Pickle",
      category: "pickles",
      price: 39,
      originalPrice: 49,
      discount: 20,
      description: "Tangy pickled yellow lemon pieces spiced with fenugreek & chilli powder.",
      isVeg: true,
      badge: "TANGY",
      prepTime: "1 min",
      rating: 4.75,
      reviewsCount: 210,
      ingredients: ["Fresh Lemons", "Salt", "Chilli Powder", "Fenugreek"],
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-pickle-5",
      name: "Garlic Pickle",
      category: "pickles",
      price: 49,
      originalPrice: 59,
      discount: 16,
      description: "Piquant garlic clove pickle in roasted spice oil gravy.",
      isVeg: true,
      badge: "GARLIC SPICE",
      prepTime: "1 min",
      rating: 4.85,
      reviewsCount: 260,
      ingredients: ["Whole Garlic", "Mustard", "Chilli", "Sesame Oil"],
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },

    // 8. COMMON EXTRAS
    {
      id: "item-extra-1",
      name: "Papad",
      category: "extras",
      price: 29,
      originalPrice: 35,
      discount: 17,
      description: "Crispy roasted / fried urad dal papad disc (2 Pcs).",
      isVeg: true,
      badge: "CRUNCHY",
      prepTime: "2 mins",
      rating: 4.8,
      reviewsCount: 340,
      ingredients: ["Urad Dal Papad"],
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-extra-2",
      name: "Onion Salad",
      category: "extras",
      price: 39,
      originalPrice: 45,
      discount: 13,
      description: "Freshly sliced raw red onion rings served with lemon wedges & green chillies.",
      isVeg: true,
      badge: "FRESH",
      prepTime: "2 mins",
      rating: 4.7,
      reviewsCount: 290,
      ingredients: ["Onions", "Lemon", "Chillies"],
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 80
    },
    {
      id: "item-extra-3",
      name: "Green Salad",
      category: "extras",
      price: 59,
      originalPrice: 69,
      discount: 14,
      description: "Garden fresh cucumber, tomato, carrot & onion slices with chat masala.",
      isVeg: true,
      badge: "HEALTHY",
      prepTime: "3 mins",
      rating: 4.65,
      reviewsCount: 180,
      ingredients: ["Cucumber", "Tomato", "Carrot", "Lemon"],
      image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 60
    },
    {
      id: "item-extra-4",
      name: "Curd",
      category: "extras",
      price: 39,
      originalPrice: 45,
      discount: 13,
      description: "Single bowl of fresh homemade thick curd (200ml).",
      isVeg: true,
      badge: "FRESH DAHI",
      prepTime: "1 min",
      rating: 4.9,
      reviewsCount: 380,
      ingredients: ["Fresh Milk Curd"],
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 80
    },
    {
      id: "item-extra-5",
      name: "Extra Ghee",
      category: "extras",
      price: 35,
      originalPrice: 40,
      discount: 12,
      description: "Pure aromatic melted cow ghee cup (30ml) for rice / biryani.",
      isVeg: true,
      badge: "PURE DESI GHEE",
      prepTime: "1 min",
      rating: 4.95,
      reviewsCount: 450,
      ingredients: ["Pure Cow Ghee"],
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 100
    },
    {
      id: "item-extra-6",
      name: "Boiled Egg",
      category: "extras",
      price: 25,
      originalPrice: 30,
      discount: 16,
      description: "Single hard-boiled farm egg sprinkled with pepper & salt.",
      isVeg: false,
      badge: "PROTEIN",
      prepTime: "2 mins",
      rating: 4.8,
      reviewsCount: 320,
      ingredients: ["Boiled Egg", "Pepper"],
      image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80",
      available: true,
      stockQty: 80
    }
  ],

  orders: [
    {
      id: "ORD-9401",
      customerName: "Rahul Sharma",
      email: "rahul.sharma@example.com",
      phone: "+91 98123 45678",
      type: "dine-in",
      tableNo: "Table 04",
      items: [
        { id: "item-biryani-1", name: "Andhra Chicken Biryani", qty: 1, price: 349 },
        { id: "item-bev-1", name: "Buttermilk (Majjiga)", qty: 2, price: 59 }
      ],
      subtotal: 467,
      tax: 23.35,
      deliveryFee: 0,
      packagingFee: 0,
      total: 490.35,
      status: "preparing",
      createdAt: "12 mins ago",
      notes: "Serve with extra Gongura pickle."
    },
    {
      id: "ORD-9402",
      customerName: "Priya Patel",
      email: "priya.p@example.com",
      phone: "+91 99876 54321",
      type: "delivery",
      address: "Flat 402, Green Glen Layout, Indiranagar, Bengaluru",
      items: [
        { id: "item-biryani-2", name: "Mutton Dum Biryani", qty: 2, price: 449 },
        { id: "item-curry-1", name: "Gongura Chicken", qty: 1, price: 329 }
      ],
      subtotal: 1227,
      tax: 61.35,
      deliveryFee: 50,
      packagingFee: 15,
      total: 1353.35,
      status: "incoming",
      createdAt: "2 mins ago",
      notes: "Ring bell twice."
    }
  ],

  customers: [
    {
      id: "CUST-101",
      name: "Rahul Sharma",
      email: "rahul.sharma@example.com",
      phone: "+91 98123 45678",
      address: "House 12, 100ft Road, Indiranagar, Bengaluru",
      totalOrders: 14,
      totalSpent: 12480,
      loyaltyPoints: 620,
      tier: "Gold VIP",
      favoriteDish: "Andhra Chicken Biryani",
      notes: "Allergic to peanuts. Prefers window seating."
    },
    {
      id: "CUST-102",
      name: "Priya Patel",
      email: "priya.p@example.com",
      phone: "+91 99876 54321",
      address: "Flat 402, Green Glen Layout, Indiranagar, Bengaluru",
      totalOrders: 8,
      totalSpent: 8900,
      loyaltyPoints: 415,
      tier: "Silver",
      favoriteDish: "Mutton Dum Biryani",
      notes: "Loves spicy Gongura chicken."
    },
    {
      id: "CUST-103",
      name: "Vikramaditya Rao",
      email: "vikram.rao@example.com",
      phone: "+91 98450 11223",
      address: "Penthouse 01, Lavelle Road, Bengaluru",
      totalOrders: 22,
      totalSpent: 28400,
      loyaltyPoints: 1420,
      tier: "Platinum Elite",
      favoriteDish: "Natukodi Pulusu",
      notes: "VIP corporate client."
    }
  ],

  reservations: [
    {
      id: "RES-501",
      guestName: "Vikramaditya Rao",
      phone: "+91 98450 11223",
      guests: 4,
      date: "2026-07-30",
      time: "20:00",
      tableAllocated: "Table 08 (Window View)",
      status: "Confirmed",
      specialRequest: "Anniversary celebration table decorations."
    },
    {
      id: "RES-502",
      guestName: "Sneha Kapoor",
      phone: "+91 98111 22334",
      guests: 2,
      date: "2026-07-30",
      time: "21:15",
      tableAllocated: "Table 02",
      status: "Confirmed",
      specialRequest: "Quiet table away from speaker."
    }
  ],

  tables: [
    { id: "T-01", name: "Table 01", capacity: 2, status: "Occupied", currentOrder: "ORD-9401" },
    { id: "T-02", name: "Table 02", capacity: 2, status: "Reserved", currentOrder: null },
    { id: "T-03", name: "Table 03", capacity: 4, status: "Available", currentOrder: null },
    { id: "T-04", name: "Table 04", capacity: 4, status: "Occupied", currentOrder: "ORD-9401" },
    { id: "T-05", name: "Table 05", capacity: 6, status: "Available", currentOrder: null },
    { id: "T-06", name: "Table 06", capacity: 6, status: "Available", currentOrder: null },
    { id: "T-07", name: "Table 07", capacity: 8, status: "Available", currentOrder: null },
    { id: "T-08", name: "Table 08", capacity: 4, status: "Reserved", currentOrder: null },
    { id: "T-09", name: "Table 09", capacity: 2, status: "Available", currentOrder: null },
    { id: "T-10", name: "Table 10", capacity: 2, status: "Available", currentOrder: null }
  ]
};

function getStore() {
  const localData = localStorage.getItem(STORAGE_KEY);
  if (!localData) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(initialStore));
    return initialStore;
  }
  try {
    const parsed = JSON.parse(localData);
    if (parsed.menuItems) {
      parsed.menuItems.forEach(i => {
        if (typeof i.stockQty === 'undefined') i.stockQty = 30;
      });
    }
    return parsed;
  } catch (e) {
    return initialStore;
  }
}

function updateStore(newStore) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(newStore));
}
